import React from 'react'
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by sauki futaki",
};
export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className='h-screen flex items-center justify-center'>{children}</div>
  )
}
