import { auth } from "@/auth";
import Navbar from "@/components/navbar";
import React from "react";
import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { Twitter, Linkedin, Github } from 'lucide-react'

const fc = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Dashboard | Vote Now`,
  description: "Generated by create next app",
};

export default async function LayoutDashboard({ children }: { children: React.ReactNode }) {
  const session = await auth();
  const user = session?.user;

  return (
    <div className={`${fc.className}`}>
      <Navbar
        urlAvatar={user?.image ?? "https://github.com/shadcn.png"}
        userName={user?.name ?? "stranger"}
        email={user?.email ?? ""}
        userRole={user?.role ?? ""}
      />
      <div>
        {children}
      </div>
      <footer className="bg-black text-gray-400">
      <div className="container mx-auto px-4 py-12">
        <div className="flex flex-col md:flex-row justify-between">
          {/* Left Section */}
          <div className="mb-8 md:mb-0">
            <Link href="/" className="flex items-center gap-2 text-white mb-4">
              <Image
                src="/placeholder.svg"
                alt="Voting App Logo"
                width={32}
                height={32}
                className="dark:invert"
              />
              <span className="font-semibold">Voting App</span>
            </Link>
            <div className="space-y-1">
              <p>Copyright © {new Date().getFullYear()} Voting App</p>
              <p>All rights reserved</p>
            </div>
          </div>

          {/* Right Section - Navigation Links */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-16">
            {/* Company Links */}
            <div className="space-y-4">
              <Link href="/pricing" className="block hover:text-white transition-colors">
                Pricing
              </Link>
              <Link href="/blog" className="block hover:text-white transition-colors">
                Blog
              </Link>
              <Link href="/contact" className="block hover:text-white transition-colors">
                Contact
              </Link>
            </div>

            {/* Legal Links */}
            <div className="space-y-4">
              <Link href="/privacy" className="block hover:text-white transition-colors">
                Privacy Policy
              </Link>
              <Link href="/terms" className="block hover:text-white transition-colors">
                Terms of Service
              </Link>
              <Link href="/refund" className="block hover:text-white transition-colors">
                Refund Policy
              </Link>
            </div>

            {/* Social Links */}
            <div className="space-y-4">
              <Link 
                href="https://twitter.com/votingapp" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:text-white transition-colors"
              >
                <Twitter className="h-4 w-4" />
                Twitter
              </Link>
              <Link 
                href="https://linkedin.com/company/votingapp" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:text-white transition-colors"
              >
                <Linkedin className="h-4 w-4" />
                LinkedIn
              </Link>
              <Link 
                href="https://github.com/votingapp" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-2 hover:text-white transition-colors"
              >
                <Github className="h-4 w-4" />
                GitHub
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
    </div>
  );
}
